### ISSUE TITLE
Newb instructions

### ISSUE THREAD

**Issue by kumavis** [jed/dynamo-down#4]
i have no idea what im doing dot jpeg
![image](https://cloud.githubusercontent.com/assets/1474978/7059932/99caf158-de2d-11e4-89e2-115e34c6210e.png)

**Comment by kumavis** [comment]
What is necessary for compatibility?

**Comment by jed** [comment]
what you've got here is fine. just a table with a hash and range, and string or binary keys.

**Comment by kumavis** [comment]
thanks :+1:
